In [2]:
#A1
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

add_result = arr + 2
multiply_result = arr * 3
divide_result = arr / 2

print("Original Array:", arr)
print("After Adding 2:", add_result)
print("After Multiplying by 3:", multiply_result)
print("After Dividing by 2:", divide_result)


Original Array: [10 20 30 40 50]
After Adding 2: [12 22 32 42 52]
After Multiplying by 3: [ 30  60  90 120 150]
After Dividing by 2: [ 5. 10. 15. 20. 25.]


In [3]:
#A2(a)
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Original Array:", arr)
print("Reversed Array:", reversed_arr)

Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]


In [10]:
#A2(b)
import numpy as np

def most_frequent(arr):
    unique_values, counts = np.unique(arr, return_counts=True)
    max_count_index = np.argmax(counts)
    most_frequent_value = unique_values[max_count_index]
    indices = np.where(arr == most_frequent_value)[0]
    return most_frequent_value, indices

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

most_x, indices_x = most_frequent(x)

print("Most Frequent in x:", most_x, "Indices:", indices_x)

Most Frequent in x: 1 Indices: [0 5 7 8 9]


In [9]:
#A2(b)
import numpy as np

def most_frequent(arr):
    unique_values, counts = np.unique(arr, return_counts=True)
    max_count_index = np.argmax(counts)
    most_frequent_value = unique_values[max_count_index]
    indices = np.where(arr == most_frequent_value)[0]
    return most_frequent_value, indices

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

most_y, indices_y = most_frequent(y)

print("Most Frequent in y:", most_y, "Indices:", indices_y)

Most Frequent in y: 1 Indices: [0 1 2]


In [11]:
#A3
import numpy as np
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])
element_1_2 = arr_2d[0, 1]
element_3_1 = arr_2d[2, 0]
print("Element at (1,2):", element_1_2)
print("Element at (3,1):", element_3_1)

Element at (1,2): 20
Element at (3,1): 70


In [13]:
#A4
import numpy as np
jessica_singh = np.linspace(10, 100, 25)

print("Array:", jessica_singh)
print("Dimensions:", jessica_singh.ndim)
print("Shape:", jessica_singh.shape)
print("Total Elements:", jessica_singh.size)
print("Data Type:", jessica_singh.dtype)
print("Total Bytes:", jessica_singh.nbytes)

transposed_array = jessica_singh.reshape(25, 1)
print("Transposed Array using reshape():\n", transposed_array)

print("Transpose using .T:\n", jessica_singh.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes: 200
Transposed Array using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using .T:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [16]:
#A5
ucs420_jessica_singh = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
mean_val = np.mean(ucs420_jessica_singh)
median_val = np.median(ucs420_jessica_singh)
max_val = np.max(ucs420_jessica_singh)
min_val = np.min(ucs420_jessica_singh)
unique_val = np.unique(ucs420_jessica_singh)

print("Mean: ", mean_val)
print("Median: ", median_val)
print("Max: ", max_val)
print("Min: ", min_val)
print("Unique: ", unique_val)

reshaped_ucs420_jessica_singh = ucs420_jessica_singh.reshape(4,3)
print("Reshaped array: ", reshaped_ucs420_jessica_singh)

resized_reshaped_ucs420_jessica_singh = np.resize(ucs420_jessica_singh,(2,3))
print("Resized array: ", resized_reshaped_ucs420_jessica_singh)

Mean:  43.333333333333336
Median:  37.5
Max:  90
Min:  10
Unique:  [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:  [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:  [[10 20 30]
 [40 50 60]]
